
export const standardPoojas = [
  {
    id: "griha-pravesh",
    name: "Griha Pravesh",
    emoji: "🏠",
    description: "House warming ceremony for a new home. Invokes blessings and positive energy.",
    duration: 180,
  },
  {
    id: "satyanarayan-puja",
    name: "Satyanarayan Puja",
    emoji: "🙏",
    description: "Worship of Lord Vishnu for prosperity, success and wellbeing of family.",
    duration: 120,
  },
  {
    id: "ganesh-puja",
    name: "Ganesh Puja",
    emoji: "🐘",
    description: "Worship of Lord Ganesha to remove obstacles and bring success.",
    duration: 90,
  },
  {
    id: "lakshmi-puja",
    name: "Lakshmi Puja",
    emoji: "💰",
    description: "Worship of Goddess Lakshmi for wealth and prosperity.",
    duration: 90,
  },
  {
    id: "navgraha-shanti",
    name: "Navgraha Shanti",
    emoji: "🌠",
    description: "Pacification of the nine planets to remove obstacles and negative influences.",
    duration: 150,
  },
  {
    id: "durga-puja",
    name: "Durga Puja",
    emoji: "💪",
    description: "Worship of Goddess Durga for strength and protection.",
    duration: 120,
  },
  {
    id: "kali-puja",
    name: "Kali Puja",
    emoji: "⚔️",
    description: "Worship of Goddess Kali to remove negative energies and obstacles.",
    duration: 120,
  },
  {
    id: "rudra-abhishek",
    name: "Rudra Abhishek",
    emoji: "🔱",
    description: "Worship of Lord Shiva for peace, prosperity and to overcome challenges.",
    duration: 150,
  },
  {
    id: "saraswati-puja",
    name: "Saraswati Puja",
    emoji: "📚",
    description: "Worship of Goddess Saraswati for knowledge, wisdom, and education.",
    duration: 90,
  },
  {
    id: "janmashtami-puja",
    name: "Janmashtami Puja",
    emoji: "👶",
    description: "Celebration of Lord Krishna's birth with special rituals and prayers.",
    duration: 120,
  },
  {
    id: "diwali-puja",
    name: "Diwali Puja",
    emoji: "🪔",
    description: "Festival of lights celebration with Lakshmi-Ganesh worship for prosperity.",
    duration: 90,
  },
  {
    id: "ram-navami",
    name: "Ram Navami",
    emoji: "🏹",
    description: "Celebration of Lord Rama's birth with special rituals and prayers.",
    duration: 120,
  },
  {
    id: "hanuman-puja",
    name: "Hanuman Puja",
    emoji: "🐒",
    description: "Worship of Lord Hanuman for strength, courage and protection.",
    duration: 90,
  },
  {
    id: "vastu-shanti",
    name: "Vastu Shanti",
    emoji: "🏡",
    description: "Purification and energetic balancing of living or working spaces.",
    duration: 180,
  },
  {
    id: "vivah-havan",
    name: "Vivah (Wedding) Ceremony",
    emoji: "💍",
    description: "Traditional Hindu wedding rituals and ceremonies.",
    duration: 240,
  },
];
