
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvahgeulbmesseopsmrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52YWhnZXVsYm1lc3Nlb3BzbXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzM2ODgsImV4cCI6MjA2MzMwOTY4OH0.nA2PkeHiy06IMThaxh-Vxz-BLvWBoiwb0WY2DPoMmiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
